---
title: "twi_sentiment"
author: "YIN LONG"
output: html_document
---
```{r}
library(readxl)
library(data.table)
```
```{r}
twi <-  read_excel("E:/DV/pro\\DV_sentiment_NEW.xlsx")
twi<-as.data.table(twi)
```
```{r}
library(tidyverse)
library(igraph)
library(dplyr)
library(ggthemes)
library(ggplot2)
library(igraph)
library(tibble)
library(plotly)
library(network)
library(DT)
library(wordcloud)
library(sna)
library(ndtv)
library(visNetwork)
library(ggrepel)
library(networkD3)
library(gridExtra)
```

```{r}
twi<-twi%>%
mutate(Sentiment=ifelse(sentiment>= 0.05,"positive",ifelse(sentiment <= -0.05,"negative","neutral")))
```
```{r}
twi<-twi%>%
mutate(twi_date=as.Date(twi$date,format="%Y-%m-%d"))%>%
mutate(td= format(as.Date(twi_date, "%m/%d/%Y"),"%Y-%m"))
```


# first one
```{r}
three<-twi%>%
  select(Sentiment)%>%
  group_by(Sentiment)%>%
  count(Sentiment)
```

```{r}
ggplot(three, aes(x=Sentiment, y=n, fill=Sentiment)) +
  geom_bar(stat="identity")+theme_minimal()+labs(x = "Sentiment Categories", y = "Number of Tweets",
       title = "Sentiment State Distribution of Tweets")+theme(legend.position="none")
```
```{r}
num<-twi%>%
  select(twi_date,Sentiment)%>%
  group_by(twi_date,Sentiment)%>%
  count(twi_date,Sentiment)
```

```{r}
ggplot(num, aes(x = twi_date, y = n,colour= Sentiment)) +
  geom_line(size=1.2)+ geom_vline(xintercept=as.numeric(as.Date("2021-03-01")), linetype="dashed", 
                color = "black", size=0.8)+ scale_x_date(breaks = "25 day")+ geom_vline(xintercept=as.numeric(as.Date("2021-02-06")), linetype="dashed", 
                color = "black", size=0.8)+theme_minimal()+labs(x = "Date of Tweets", y = "Number of Tweets",
       title = "Timeline showing Sentiment of Tweets about COVID-19 Vaccines") +annotate("text", x = as.Date("2020-12-16"), y = 10, label = "2020-12-12")+annotate("text", x = as.Date("2021-03-01"), y = 750, label = "2021-03-01")+annotate("text", x = as.Date("2021-02-06"), y = 750, label = "2021-02-06")
```


# second one

```{r}
pos <-  read_csv("E:/DV/pro/twi/pos.csv")
neu <-  read_csv("E:/DV/pro/twi/neu.csv")
neg <-  read_csv("E:/DV/pro/twi/neg.csv")
```

```{r}
set.seed(42)
wordcloud(words = pos$tokenize, freq = pos$n, min.freq = 1,
          max.words=200, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))
```

```{r}
set.seed(1)
wordcloud(words = neg$tokenize, freq = neg$n, min.freq = 1,
          max.words=200, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))
```

```{r}
set.seed(1)
wordcloud(words = neu$tokenize, freq = neu$n, min.freq = 1,
          max.words=200, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))
```




# third one
```{r}
favor<-twi%>%
  select(favorites,Sentiment)%>%
  arrange(-favorites)%>%  
  slice(1:15)
```
  
```{r}
ggplot(data=favor,aes(y=as.factor(favorites), x=favorites,fill=Sentiment) ) + 
  geom_bar(stat="identity")+labs(x = "Number of Times it was Favorited", y = "Tweets",
       title = "Sentiment State of Top 15 Popular Tweets base on favorited times ")+theme_minimal()+  theme(
        axis.text.y=element_blank(),axis.ticks.y=element_blank())+ geom_text(aes(label=paste0(favorites)), vjust=0.5,hjust=1,color='white')
```

```{r}
retwe<-twi%>%
  select(retweets,Sentiment)%>%
  arrange(-retweets)%>%  
  slice(1:15)
```
  
```{r}
ggplot(data=retwe,aes(y=as.factor(retweets), x=retweets,fill=Sentiment) ) + 
  geom_bar(stat="identity")+labs(x = "Number of Times it was Retweeted", y = "Tweets",
       title = "Sentiment State of Top 15 Popular Tweets base on retweeted times ")+theme_minimal()+ theme(
        axis.text.y=element_blank(),axis.ticks.y=element_blank())+ geom_text(aes(label=paste0(retweets)), vjust=0.5,hjust=1,color='white')
```

# forth one

```{r}
follow <-  read_csv("E:/DV/pro/twi/follow.csv")%>%
  mutate(Sentiment=sent_ca)
```


```{r}
ggplot(follow, aes(x=factor(user_name), fill=Sentiment))+
  geom_bar(width=0.7)+
  theme_minimal()+ 
  theme(axis.text.x = element_text(angle = 70, hjust = 0.5, 
                              vjust = 0.5,color = "black",size=9))+labs(x = "User Name", y = "Number of Tweets",
       title = "Sentiment State of Tweets of Top 10 Users who have most followers ")
```









